name: Design Padawan
favicon: null
layout_spectrum: 0.9192460179328918
typography_spectrum: 0.054875299567356706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5699197805952281
  lightness: 0.5964576546102762
  saturation: 0.1648220478091389
  rhythmicContrast: 0.6916652959771454
purpose: []
